bedtools intersect -wa -wb -a pMicom_in_PG_Hyper.txt -b annotations_b_hg38_eldf_promoter.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hyper.txt -b annotations_b_hg38_eldf_CGI.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hyper.txt -b annotations_b_hg38_eldf_CGshores.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hyper.txt -b annotations_b_hg38_eldf_CGshelves.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hyper.txt -b annotations_b_hg38_eldf_CGinter.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hyper.txt -b annotations_b_hg38_eldf_cds.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hyper.txt -b annotations_b_hg38_eldf_5UTR.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hyper.txt -b annotations_b_hg38_eldf_3UTR.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hyper.txt -b annotations_b_hg38_eldf_intergenic.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hyper.txt -b annotations_b_hg38_eldf_exon.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hyper.txt -b annotations_b_hg38_eldf_intron.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hyper.txt -b annotations_b_hg38_rmsk_LINE.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hyper.txt -b annotations_b_hg38_rmsk_LTR.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hyper.txt -b annotations_b_hg38_rmsk_SINE.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hyper.txt -b annotations_b_hg38_rmsk_Satellite.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hyper_C13rec_C50rec.txt -b annotations_b_hg38_eldf_promoter.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hyper_C13rec_C50rec.txt -b annotations_b_hg38_eldf_CGI.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hyper_C13rec_C50rec.txt -b annotations_b_hg38_eldf_CGshores.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hyper_C13rec_C50rec.txt -b annotations_b_hg38_eldf_CGshelves.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hyper_C13rec_C50rec.txt -b annotations_b_hg38_eldf_CGinter.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hyper_C13rec_C50rec.txt -b annotations_b_hg38_eldf_cds.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hyper_C13rec_C50rec.txt -b annotations_b_hg38_eldf_5UTR.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hyper_C13rec_C50rec.txt -b annotations_b_hg38_eldf_3UTR.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hyper_C13rec_C50rec.txt -b annotations_b_hg38_eldf_intergenic.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hyper_C13rec_C50rec.txt -b annotations_b_hg38_eldf_exon.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hyper_C13rec_C50rec.txt -b annotations_b_hg38_eldf_intron.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hyper_C13rec_C50rec.txt -b annotations_b_hg38_rmsk_LINE.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hyper_C13rec_C50rec.txt -b annotations_b_hg38_rmsk_LTR.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hyper_C13rec_C50rec.txt -b annotations_b_hg38_rmsk_SINE.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hyper_C13rec_C50rec.txt -b annotations_b_hg38_rmsk_Satellite.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo.txt -b annotations_b_hg38_eldf_promoter.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo.txt -b annotations_b_hg38_eldf_CGI.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo.txt -b annotations_b_hg38_eldf_CGshores.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo.txt -b annotations_b_hg38_eldf_CGshelves.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo.txt -b annotations_b_hg38_eldf_CGinter.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo.txt -b annotations_b_hg38_eldf_cds.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo.txt -b annotations_b_hg38_eldf_5UTR.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo.txt -b annotations_b_hg38_eldf_3UTR.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo.txt -b annotations_b_hg38_eldf_intergenic.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo.txt -b annotations_b_hg38_eldf_exon.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo.txt -b annotations_b_hg38_eldf_intron.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo.txt -b annotations_b_hg38_rmsk_LINE.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo.txt -b annotations_b_hg38_rmsk_LTR.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo.txt -b annotations_b_hg38_rmsk_SINE.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo.txt -b annotations_b_hg38_rmsk_Satellite.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo_C13rec_C50rec.txt -b annotations_b_hg38_eldf_promoter.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo_C13rec_C50rec.txt -b annotations_b_hg38_eldf_CGI.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo_C13rec_C50rec.txt -b annotations_b_hg38_eldf_CGshores.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo_C13rec_C50rec.txt -b annotations_b_hg38_eldf_CGshelves.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo_C13rec_C50rec.txt -b annotations_b_hg38_eldf_CGinter.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo_C13rec_C50rec.txt -b annotations_b_hg38_eldf_cds.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo_C13rec_C50rec.txt -b annotations_b_hg38_eldf_5UTR.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo_C13rec_C50rec.txt -b annotations_b_hg38_eldf_3UTR.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo_C13rec_C50rec.txt -b annotations_b_hg38_eldf_intergenic.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo_C13rec_C50rec.txt -b annotations_b_hg38_eldf_exon.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo_C13rec_C50rec.txt -b annotations_b_hg38_eldf_intron.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo_C13rec_C50rec.txt -b annotations_b_hg38_rmsk_LINE.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo_C13rec_C50rec.txt -b annotations_b_hg38_rmsk_LTR.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo_C13rec_C50rec.txt -b annotations_b_hg38_rmsk_SINE.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PG_Hypo_C13rec_C50rec.txt -b annotations_b_hg38_rmsk_Satellite.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper.txt -b annotations_b_hg38_eldf_promoter.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper.txt -b annotations_b_hg38_eldf_CGI.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper.txt -b annotations_b_hg38_eldf_CGshores.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper.txt -b annotations_b_hg38_eldf_CGshelves.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper.txt -b annotations_b_hg38_eldf_CGinter.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper.txt -b annotations_b_hg38_eldf_cds.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper.txt -b annotations_b_hg38_eldf_5UTR.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper.txt -b annotations_b_hg38_eldf_3UTR.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper.txt -b annotations_b_hg38_eldf_intergenic.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper.txt -b annotations_b_hg38_eldf_exon.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper.txt -b annotations_b_hg38_eldf_intron.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper.txt -b annotations_b_hg38_rmsk_LINE.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper.txt -b annotations_b_hg38_rmsk_LTR.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper.txt -b annotations_b_hg38_rmsk_SINE.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper.txt -b annotations_b_hg38_rmsk_Satellite.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper_C7rec_C35rec.txt -b annotations_b_hg38_eldf_promoter.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper_C7rec_C35rec.txt -b annotations_b_hg38_eldf_CGI.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper_C7rec_C35rec.txt -b annotations_b_hg38_eldf_CGshores.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper_C7rec_C35rec.txt -b annotations_b_hg38_eldf_CGshelves.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper_C7rec_C35rec.txt -b annotations_b_hg38_eldf_CGinter.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper_C7rec_C35rec.txt -b annotations_b_hg38_eldf_cds.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper_C7rec_C35rec.txt -b annotations_b_hg38_eldf_5UTR.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper_C7rec_C35rec.txt -b annotations_b_hg38_eldf_3UTR.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper_C7rec_C35rec.txt -b annotations_b_hg38_eldf_intergenic.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper_C7rec_C35rec.txt -b annotations_b_hg38_eldf_exon.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper_C7rec_C35rec.txt -b annotations_b_hg38_eldf_intron.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper_C7rec_C35rec.txt -b annotations_b_hg38_rmsk_LINE.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper_C7rec_C35rec.txt -b annotations_b_hg38_rmsk_LTR.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper_C7rec_C35rec.txt -b annotations_b_hg38_rmsk_SINE.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hyper_C7rec_C35rec.txt -b annotations_b_hg38_rmsk_Satellite.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo.txt -b annotations_b_hg38_eldf_promoter.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo.txt -b annotations_b_hg38_eldf_CGI.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo.txt -b annotations_b_hg38_eldf_CGshores.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo.txt -b annotations_b_hg38_eldf_CGshelves.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo.txt -b annotations_b_hg38_eldf_CGinter.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo.txt -b annotations_b_hg38_eldf_cds.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo.txt -b annotations_b_hg38_eldf_5UTR.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo.txt -b annotations_b_hg38_eldf_3UTR.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo.txt -b annotations_b_hg38_eldf_intergenic.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo.txt -b annotations_b_hg38_eldf_exon.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo.txt -b annotations_b_hg38_eldf_intron.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo.txt -b annotations_b_hg38_rmsk_LINE.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo.txt -b annotations_b_hg38_rmsk_LTR.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo.txt -b annotations_b_hg38_rmsk_SINE.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo.txt -b annotations_b_hg38_rmsk_Satellite.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo_C7rec_C35rec.txt -b annotations_b_hg38_eldf_promoter.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo_C7rec_C35rec.txt -b annotations_b_hg38_eldf_CGI.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo_C7rec_C35rec.txt -b annotations_b_hg38_eldf_CGshores.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo_C7rec_C35rec.txt -b annotations_b_hg38_eldf_CGshelves.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo_C7rec_C35rec.txt -b annotations_b_hg38_eldf_CGinter.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo_C7rec_C35rec.txt -b annotations_b_hg38_eldf_cds.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo_C7rec_C35rec.txt -b annotations_b_hg38_eldf_5UTR.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo_C7rec_C35rec.txt -b annotations_b_hg38_eldf_3UTR.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo_C7rec_C35rec.txt -b annotations_b_hg38_eldf_intergenic.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo_C7rec_C35rec.txt -b annotations_b_hg38_eldf_exon.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo_C7rec_C35rec.txt -b annotations_b_hg38_eldf_intron.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo_C7rec_C35rec.txt -b annotations_b_hg38_rmsk_LINE.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo_C7rec_C35rec.txt -b annotations_b_hg38_rmsk_LTR.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo_C7rec_C35rec.txt -b annotations_b_hg38_rmsk_SINE.txt | sort -k4,4 -u | wc -l
bedtools intersect -wa -wb -a pMicom_in_PR_Hypo_C7rec_C35rec.txt -b annotations_b_hg38_rmsk_Satellite.txt | sort -k4,4 -u | wc -l
